name: deploy-prod

on:
  push:
    branches: [prod]

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      environment: prod
    secrets: inherit
